#!/bin/bash

FN="./dayssince"

# these are relative and will be have to be adjusted for each different day you want to run the tests
Q1="8/7"		A1=0
Q2="15/7"		A2=-7
Q3="1/7"		A3=7

Q4="+7"			A4="15/7/2018"
Q5="+180"		A5="4/1/2019"
Q6="-30"		A6="8/6/2018"

# these tests should produce the same results no matter what day you run them
Q7="1/9 +10"		A7="11/9/2018"
Q8="1/9 -10"		A8="22/8/2018"
Q9="9/1/2019 +30"	A9="8/2/2019"

Q10="11/8 8/11"		A10="89"
Q11="10/12 9/1"		A11="-335"
Q12="7/7/2018 8/7/2018"	A12="1"

LASTTEST=12
FAIL=0

onlyDigits() {
        case $1 in *[!-0-9]*) false;; esac
}

#usage: expect $a $b $failure_message
function expect {
	if onlyDigits "$2"; then
		if [ "$1" -ne "$2" ]; then
			echo "	FAIL: $3"
			let FAIL++
		fi
	else
		if [ "$1" != "$2" ]; then
			echo "	FAIL: $3"
			let FAIL++
		fi
	fi
}


for (( n=1 ; n <= $LASTTEST ; n++))
do
	question="$( eval echo \$Q$n )"
	answer="$( eval echo \$A$n )"
	result=$( $FN $question )
	expect "$result" "$answer" "Test $n: $FN $question GOT ==> $result EXPECTED ==> $answer"
done
if [ $FAIL -eq 0 ]; then
	echo ALL TESTS PASSED
fi
